spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/pdpmigration?currentSchema=sb_flyway'
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true