
spring:
  datasource:
    url: jdbc:h2:mem:~
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  cache:
    redis:
      time-to-live: 10m
  data:
    redis:
      host: localhost
      port: 6379
