
hateoas:
  url:
    base: http://localhost:9088/api/posts/
logging:
  level:
    org.zalando.logbook : trace
    org:
      springframework:
        web:
          client:
            RestTemplate: trace
logbook:
  exclude:
    - /api/posts/comment
    - /api/upload
    - /api/download
