spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/pdpmigration?currentSchema=sb_liquibase'
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true